### PR TITLE
Add autocommand to inform user the update/install finished

### LINKED ISSUE #4: Installation/Update complete event
I update my tools very frequently with some scripts. I think would be nice to have an event that the user could attach an action for when the installations/updating is complete. Something similar to what packer does: https://github.com/wbthomason/packer.nvim#user-autocommands

This way I could nest all the package/toolings update and then quit neovim, like:

```
nvim --headless \
  -c 'autocmd User PackerComplete MasonToolsUpdate' \
  -c 'autocmd User MasonToolsComplete quitall!' \
  -c 'PackerSync'
```

What do you think?

### PR DESCRIPTION
**Pull request by kassio**
Fixes #4

### CODE REVIEW

**Comment by WhoIsSethDaniel** [comment]
Thanks for the PR. Apologies for the late reply. 

As I read it (haven't tested it) this will only work if nvim is headless (because mason will run in synchronous mode if nvim starts headless, but will run asynchronously if nvim is not headless). If nvim is *not* headless this user autocommand will still be triggered. I doubt that's what you want since the autocommand will be triggered before anything is installed.  We'll probably have to surround the new code with something that detects headless mode and only triggers the user autocommand then. You also don't need to use `vim.cmd`. You can use `vim.api.nvim_exec_autocommands`. I also wonder if the autocommand should be triggered if nothing has been installed, but I'm not too worried about that.

So maybe the code should look something like this (entirely untested):
```lua
if #vim.api.nvim_list_uis() == 0 then
  vim.api.nvim_exec_autocommands('User MasonToolsUpdateCompleted', {})
end
```

**Comment by kassio** [comment]
@WhoIsSethDaniel, thanks for the review. I added the missing `if`. Can you take another look, please?

**Comment by williamboman** [comment]
Hey! Happened to see this. The Lua API is never synchronous, regardless of whether Neovim is running in headless mode or not. It's only the command API (i.e. `:MasonInstall`) that [is synchronous when headless](https://github.com/williamboman/mason.nvim/blob/924923882bcc027268fdfb77e72df60b058d5e69/lua/mason/api/command.lua#L78-L28).

**Comment by williamboman** [comment]
What you could try is something like

```lua
local function install_packages(packages)
  local completed = 0
  local total = vim.tbl_count(packages)

  for pkg, version in pairs(packages) do
    pkg:install({ version = version }):once("closed", function ()
      completed = completed + 1
      if completed >= total then
            vim.api.nvim_exec_autocommands("User MasonToolsUpdateCompleted", { data = { packages = packages } })
      end
    end)
  end
end
```

**Comment by WhoIsSethDaniel** [comment]
@williamboman that's unexpected. Do they actually have different code paths? I assume they share at least some code.

**Comment by kassio** [comment]
@WhoIsSethDaniel, I updated the code based on the suggestion above. What do you think?

**Comment by williamboman** [comment]
> @williamboman that's unexpected. Do they actually have different code paths? I assume they share at least some code.

The command API is just a wrapper around the very same Lua APIs. All kinds of asynchronous operations in Mason are non-blocking, as to not hog the event loop. `:MasonInstall` will block the main loop (i.e. freeze the entire editor) via `vim.wait` when called in headless mode, in order to make headless installations a bit more seamless (`$ nvim --headless -c "MasonInstall my-pkg" -c "qall"`).

**Comment by kassio** [comment]
I actually reverted the last commit. In my flow, at least, I don't care to much if anything was updated. I just wan't to be able to trigger another action when Mason finished its jobs.

**Comment by WhoIsSethDaniel** [comment]
I figured out what I was doing wrong. I was putting schedule_wrap in the wrong place. It works now. I'll submit and merge soon.

**Comment by WhoIsSethDaniel** [comment]
@kassio i gave you co-authorship on #10 which I hope will close out #4. I am going to close this PR. Thanks.

**Comment by williamboman** [comment]
> I have a branch that does something like what @williamboman suggested. It seems to work except that the triggering of the event seems to be dropped or missed somehow. The code [here](https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim/blob/2f0edcfb6f97d54ea2d95c00ba5c7ea6d5b1c427/lua/mason-tool-installer/init.lua#L46-L53) definitely runs, but an event handler I have setup doesn't see it. As of now I have no idea why. I can trigger the event by manually running either `:doautocmd` or `:lua vim.api.nvim_exec_autocmds(...)`.

Did you need to schedule this callback for it to start working? Most likely it was throwing an error because the callback was invoked outside of Neovims main loop, where API functions are disabled. If this is the case, it really should produce some errors that are visible somehow... will look into it.

**Pull request closed without merging**
