### PR TITLE
Use vim.notify() instead of print()

### PR DESCRIPTION
**Pull request by dsully**

### CODE REVIEW

**Comment by WhoIsSethDaniel** [comment]
I think this is a good idea, however I receive an error when I use this change:
```
[mason-tool-installer] editorconfig-checker: installing
vim/_editor.lua:0: E5560: nvim_echo must not be called in a lua loop callback
```
I don't have anything that overrides notify.

**Comment by dsully** [comment]
I'd guess because of the `vim.schedule_wrap(...)` - what's the reason for having that there?

**Comment by WhoIsSethDaniel** [comment]
You may also want to consider using a log level for the `vim.notify` and also replacing the use of `vim.api.nvim_err_writeln()` in `show_error` with `vim.notify` and a log level of `vim.log.level.ERROR`. e.g.

```lua
local show = vim.schedule_wrap(function(msg)
  vim.notify(string.format('[mason-tool-installer] %s', msg), vim.log.levels.INFO)
end)

local show_error = vim.schedule_wrap(function(msg)
  vim.notify(string.format('[mason-tool-installer] %s', msg), vim.log.levels.INFO)
end)
```

**Comment by dsully** [comment]
Updated.

**Comment by WhoIsSethDaniel** [comment]
Looks good. Thank you!

**Pull request merged**
